#version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    image: mysql:latest
    expose:
      - 3036
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
# volumes:
#   mysql: {}
